---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Get OS
      shell: uname
      args:
        executable: /bin/bash
      register: get_os
  roles:
    - role: mac
      when: get_os.stdout == "Darwin"
