---
- name: Install packages
  include: install-packages.yml

- name: Install zsh-git-prompt
  include: install-zsh-git-prompt.yml

- name: Install dotfiles
  include: install-dotfiles.yml

- name: Install asdf
  include: install-asdf.yml
  tags:
    - asdf

- name: Install ops tools
  include: install-ops-tools.yml
  tags:
    - ops

- name: Install nvm
  include: nvm.yml

- name: Install global npm packages
  include: npm-packages.yml
