---
- name: Install software using brew
  homebrew:
    name:
      - "coreutils"
      - "ctags-exuberant" # required for haskell-vim-now
      - "jq"
      - "pwgen"
      - "reattach-to-user-namespace"
      - "tmux"
      - "wget"
    update_homebrew: true

- name: Install software using brew cask
  homebrew_cask:
    name:
      - "firefox"
      - "iterm2"
