---
- name: Install packages
  include: install-packages.yaml

- name: Install zsh-git-prompt
  include: install-zsh-git-prompt.yaml

- name: Install dotfiles
  include: install-dotfiles.yml

- name: Install asdf
  include: install-asdf.yaml
  tags:
    - asdf

- name: Install ops tools
  include: install-ops-tools.yaml
  tags:
    - ops

- name: Install nvm
  include: nvm.yaml

- name: Install global npm packages
  include: npm-packages.yaml
