---
- name: Set fact to store global npm packages
  ansible.builtin.set_fact:
    global_npm_packages:
      - jsonlint

- name: Install global npm packages
  ansible.builtin.shell: |
    export NVM_DIR="${HOME}"/.nvm
    [ -s "${NVM_DIR}"/nvm.sh ] && source "${NVM_DIR}"/nvm.sh
    nvm use {{ nodejs_version }}
    npm install -g {{ item }}
  args:
    executable: /bin/bash
  # technically changed_when false is false sometimes; we just add it to
  # appease ansible-lint
  changed_when: false
  loop: "{{ global_npm_packages }}"
